runtime: python39  # Python 버전에 맞게 설정

entrypoint: gunicorn -b :$PORT backend.app:app  # gunicorn을 사용하여 애플리케이션 실행

instance_class: F2  # 인스턴스 클래스 설정 (선택적)

env_variables:
  SQLALCHEMY_DATABASE_URI: "mysql://database:K19712492Sj@34.64.32.1:3306/hangman-data"  # 실제 데이터베이스 정보로 변경

handlers:
- url: /frontend
  static_dir: frontend
- url: /
  static_files: frontend/index/index.html
  upload: frontend/index/index.html
- url: /index
  static_files: frontend/index
  upload: frontend/index

- url: /main
  static_files: frontend/main
  upload: frontend/main

- url: /leaderboard
  static_files: frontend/leaderboard
  upload: frontend/leaderboard
- url: /.*
  script: auto  # 모든 URL을 애플리케이션으로 라우팅

automatic_scaling:
  target_cpu_utilization: 0.65  # 자동 스케일링 설정 (선택적)