runtime: python39  # 사용하는 Python 버전에 따라 변경
instance_class: F2
entrypoint: gunicorn -b :$PORT -w 4 app:blueprint  # main.py 파일에 있는 Flask 앱을 실행

env_variables:
  SQLALCHEMY_DATABASE_URI: "mysql://database:K19712492Sj*@34.64.32.1/hangman-data"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
- url: /frontend
  static_dir: frontend

- url: /.*
  script: auto

  

spec:
  template:
    metadata:
      labels:
        client.knative.dev/nonce: 0cc8bb11-7447-4f83-8e58-8780470b0e00
        run.googleapis.com/startupProbeType: Default
      annotations:
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/cloudsql-instances: 'hangman-id:asia-northeast3:database'
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/startup-cpu-boost: 'true'
  traffic:
  - percent: 100
    latestRevision: true