runtime: python39  # 사용하는 Python 버전에 따라 변경
instance_class: F2
entrypoint: gunicorn -b :$PORT app.py:blueprint  # main.py 파일에 있는 Flask 앱을 실행

env_variables:
  FLASK_ENV: "production"
  SQLALCHEMY_DATABASE_URI: 'mysql+mysqldb://database:K19712492Sj*@34.64.32.1:3306/hangman-data'

handlers:
- url: /frontend
  static_dir: frontend

- url: /.*
  script: auto
