runtime: python39  # Python 버전에 맞게 설정
env: flex
entrypoint: gunicorn -b :$PORT app:app  # gunicorn을 사용하여 애플리케이션 실행

env_variables:
  SQLALCHEMY_DATABASE_URI: "mysql://database:K19712492Sj@34.64.32.1:3306/hangman-data"  # 실제 데이터베이스 정보로 변경

handlers:
- url: /.*
  script: auto  # 모든 URL을 애플리케이션으로 라우팅
- url: /
  static_files: frontend/index/index.html
  upload: frontend/index/index.html
- url: /imgs
  static_dir: frontend/imgs
- url: /index
  static_dir: frontend/index
- url: /main
  static_dir: frontend/main
- url: /leaderboard
  static_dir: frontend/leaderboard